M48
; DRILL file {KiCad (6.0.2)} date Sat Jan 21 08:28:22 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-21T08:28:22+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X110.236Y-104.14
X110.236Y-156.464
X183.388Y-103.632
X183.388Y-156.464
T0
M30
